eks_container: &CONTAINER_DEFINITION
  image: ${CIRRUS_AWS_ACCOUNT}.dkr.ecr.eu-central-1.amazonaws.com/base:j17-g7-latest
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  region: eu-central-1
  namespace: default

build_task:
  eks_container:
    <<: *CONTAINER_DEFINITION
    cpu: 2
    memory: 2G
  main_script:
    - hello
aws_credentials:
  role_arn: arn:aws:iam::275878209202:role/approles/CirrusCI-11
  role_session_name: cirrus
  region: eu-central-1
ec2_instance:
  subnet_filters:
    - name: tag:Product
      values:
        - CirrusCI
    - name: tag:EnvType
      values:
        - prod
    - name: tag:EnvName
      values:
        - prod
    - name: tag:version
      values:
        - 6
    - name: tag:aws-cdk:subnet-name
      values:
        - PrivateSubnet
  image_owners:
    - self
    - "275878209202"
    - "166916561812"
    - "460386131003"
eks_container:
  builder_subnet_filters:
    - name: tag:Product
      values:
        - CirrusCI
    - name: tag:EnvType
      values:
        - prod
    - name: tag:EnvName
      values:
        - prod
    - name: tag:version
      values:
        - 6
    - name: tag:aws-cdk:subnet-name
      values:
        - PrivateSubnet
  nodeSelectorTerms:
    - matchExpressions:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - m7a.8xlarge
            - c7a.8xlarge
            - r7a.8xlarge
  builder_image_owners:
    - self
    - "275878209202"
    - "166916561812"
    - "460386131003"
env:
  CIRRUS_AWS_ACCOUNT: "275878209202"
  CIRRUS_CLUSTER_NAME: CirrusCI-11
  CIRRUS_AGENT_VERSION: 1.136.0
