version: 1.0.{build}

branches:
  only:
  - master

cache:
  # Note that we don't use cache for local Maven repository - see https://github.com/SonarSource/sonar-java/pull/525
  - C:\Users\appveyor\maven -> appveyor.yml

install:
  - set MAVEN_VERSION=3.2.5
  # Note that indentation is important here:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\Users\appveyor\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          "http://www.apache.org/dyn/closer.cgi?action=download&filename=maven/maven-3/$($env:MAVEN_VERSION)/binaries/apache-maven-$($env:MAVEN_VERSION)-bin.zip",
          "C:\Users\appveyor\maven.zip"
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\Users\appveyor\maven.zip", "C:\Users\appveyor\maven")
      }
  - set PATH=%PATH%;C:\Users\appveyor\maven\apache-maven-%MAVEN_VERSION%\bin
  - echo %JAVA_HOME%
  - if "%RUN%" == "ruling" (git submodule update --init --recursive)

environment:
  token:
    secure: Rt4VQ6Vg/oGHkipocKlpJg==

build_script:
  - ps: ./appveyor.ps1

test: off

notifications:
- provider: Webhook
  url: https://cix.sonarsource.com/buildByToken/buildWithParameters?job=travisci-hook&token={{token}}&delay=0sec
  on_build_success: true