name: Cleanup caches and artifacts on PR close
on:
  pull_request:
    types:
      - closed

env:
  CACHE_BACKEND: s3

jobs:
  cleanup:
    runs-on: sonar-xs-public
    permissions:
      actions: write
    steps:
      - uses: SonarSource/ci-github-actions/pr_cleanup@master
