---
on:
  pull_request:

jobs:
  pre-commit:
    name: "pre-commit"
    runs-on: sonar-s
    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit
      - uses: SonarSource/gh-action_pre-commit@master # dogfood
        with:
          extra-args: --from-ref=origin/${{ github.event.pull_request.base.ref }} --to-ref=${{ github.event.pull_request.head.sha }}
