name: sonar-release (dry-run)
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  dry_run:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@5.1.5
    with:
      dryRun: true
      publishJavadoc: true
      publishToBinaries: true
      mavenCentralSync: true
