name: sonar-release (dry-run)
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  dry_run:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@c08ed43ac288fd9850a07521e63157b53cad9296 # 5.1.1
    with:
      dryRun: true
      publishToBinaries: true
      mavenCentralSync: true
