name: sonar-release (dry-run)
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  dry_run:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@feature/svermeille/BUILD-2699-do-not-use-deprecated-set-output # custom branch used for testing purpose
    with:
      dryRun: true
      publishToBinaries: true
      mavenCentralSync: true
