name: sonar-release (dry-run)
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  dry_run:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@6de7cbd29e934a2b199714856bc3846fca88cd44 # 5.1.5
    with:
      dryRun: true
      publishToBinaries: true
      mavenCentralSync: true
