name: Release

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@master # dogfood
    with:
      version: ${{ inputs.version }}
      publishToBinaries: true
      mavenCentralSync: true
      publicRelease: true
      publishJavadoc: true
      isDummyProject: true
