name: Release

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@master # dogfood
    with:
      version: ${{ inputs.version }}
      publishToBinaries: true
      mavenCentralSync: true
      publicRelease: true
      publishJavadoc: true
      isDummyProject: true

  update-release-channel:
    name: Update 'latest' release channel pointer
    needs: release
    runs-on: sonar-xs
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: SonarSource/ci-github-actions/update-release-channel@master # dogfood
        with:
          version: ${{ inputs.version }}
          channel: latest
          product: sonar-dummy-gradle-oss-plugin
