name: sonar-release (dry-run)
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  dry_run:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@66a34c7817fc1684b80badc4326de58c334133de # 5.0.10
    with:
      dryRun: true
      publishToBinaries: true
      mavenCentralSync: true
