name: sonar-release (dry-run)
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  dry_run:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@82ea072237a28d2c3702244b886995dd757911a4 # 5.1.2
    with:
      dryRun: true
      publishToBinaries: true
      mavenCentralSync: true
