name: Unified Dogfooding scans
on:
  schedule:
    # Run the workflow every day at 04:00 UTC
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  CACHE_BACKEND: s3

jobs:
  build:
    runs-on: sonar-s
    name: Build and run shadow scans
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: SonarSource/ci-github-actions/build-gradle@master # dogfood
        with:
          run-shadow-scans: true
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@master # dogfood
        with:
          primary_project_key: "SonarSource_sonar-dummy-gradle-oss"
          primary_platform: "SQC-EU"
          shadow1_project_key: "SonarSource_sonar-dummy-gradle-oss"
          shadow1_platform: "Next"
          shadow2_project_key: "SonarSource_sonar-dummy-gradle-oss"
          shadow2_platform: "SQC-US"
